/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as VetRouteImport } from './routes/vet'
import { Route as TutorIndexRouteImport } from './routes/tutor.index'
import { Route as TutorLembretesRouteImport } from './routes/tutor.lembretes'
import { Route as TutorPerfilRouteImport } from './routes/tutor.perfil'
import { Route as TutorTeleconsultasRouteImport } from './routes/tutor.teleconsultas'
import { Route as VetIndexRouteImport } from './routes/vet.index'
import { Route as VetPerfilRouteImport } from './routes/vet.perfil'
import { Route as VetPetsRouteImport } from './routes/vet.pets'
import { Route as VetTeleconsultasRouteImport } from './routes/vet.teleconsultas'
import { Route as VetTutoresRouteImport } from './routes/vet.tutores'
import { Route as TutorPetsPetIdRouteImport } from './routes/tutor.pets.$petId'
import { Route as TutorTeleconsultasIndexRouteImport } from './routes/tutor.teleconsultas.index'
import { Route as TutorTeleconsultasIdRouteImport } from './routes/tutor.teleconsultas.$id'
import { Route as VetPetsIndexRouteImport } from './routes/vet.pets.index'
import { Route as VetPetsPetIdRouteImport } from './routes/vet.pets.$petId'
import { Route as VetTeleconsultasIndexRouteImport } from './routes/vet.teleconsultas.index'
import { Route as VetTeleconsultasIdRouteImport } from './routes/vet.teleconsultas.$id'
import { Route as VetTutoresIndexRouteImport } from './routes/vet.tutores.index'
import { Route as VetTutoresTutorIdRouteImport } from './routes/vet.tutores.$tutorId'
import { Route as TutorTeleconsultasIdIndexRouteImport } from './routes/tutor.teleconsultas.$id.index'
import { Route as TutorTeleconsultasIdLiveRouteImport } from './routes/tutor.teleconsultas.$id.live'
import { Route as VetTeleconsultasIdIndexRouteImport } from './routes/vet.teleconsultas.$id.index'
import { Route as VetTeleconsultasIdFinalizarRouteImport } from './routes/vet.teleconsultas.$id.finalizar'
import { Route as VetTeleconsultasIdLiveRouteImport } from './routes/vet.teleconsultas.$id.live'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const VetRoute = VetRouteImport.update({
  id: '/vet',
  path: '/vet',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorIndexRoute = TutorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TutorRoute,
} as any)
const TutorLembretesRoute = TutorLembretesRouteImport.update({
  id: '/lembretes',
  path: '/lembretes',
  getParentRoute: () => TutorRoute,
} as any)
const TutorPerfilRoute = TutorPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => TutorRoute,
} as any)
const TutorTeleconsultasRoute = TutorTeleconsultasRouteImport.update({
  id: '/teleconsultas',
  path: '/teleconsultas',
  getParentRoute: () => TutorRoute,
} as any)
const VetIndexRoute = VetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VetRoute,
} as any)
const VetPerfilRoute = VetPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => VetRoute,
} as any)
const VetPetsRoute = VetPetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => VetRoute,
} as any)
const VetTeleconsultasRoute = VetTeleconsultasRouteImport.update({
  id: '/teleconsultas',
  path: '/teleconsultas',
  getParentRoute: () => VetRoute,
} as any)
const VetTutoresRoute = VetTutoresRouteImport.update({
  id: '/tutores',
  path: '/tutores',
  getParentRoute: () => VetRoute,
} as any)
const TutorPetsPetIdRoute = TutorPetsPetIdRouteImport.update({
  id: '/pets/$petId',
  path: '/pets/$petId',
  getParentRoute: () => TutorRoute,
} as any)
const TutorTeleconsultasIndexRoute = TutorTeleconsultasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TutorTeleconsultasRoute,
} as any)
const TutorTeleconsultasIdRoute = TutorTeleconsultasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TutorTeleconsultasRoute,
} as any)
const VetPetsIndexRoute = VetPetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VetPetsRoute,
} as any)
const VetPetsPetIdRoute = VetPetsPetIdRouteImport.update({
  id: '/$petId',
  path: '/$petId',
  getParentRoute: () => VetPetsRoute,
} as any)
const VetTeleconsultasIndexRoute = VetTeleconsultasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VetTeleconsultasRoute,
} as any)
const VetTeleconsultasIdRoute = VetTeleconsultasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VetTeleconsultasRoute,
} as any)
const VetTutoresIndexRoute = VetTutoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VetTutoresRoute,
} as any)
const VetTutoresTutorIdRoute = VetTutoresTutorIdRouteImport.update({
  id: '/$tutorId',
  path: '/$tutorId',
  getParentRoute: () => VetTutoresRoute,
} as any)
const TutorTeleconsultasIdIndexRoute =
  TutorTeleconsultasIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TutorTeleconsultasIdRoute,
  } as any)
const TutorTeleconsultasIdLiveRoute =
  TutorTeleconsultasIdLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => TutorTeleconsultasIdRoute,
  } as any)
const VetTeleconsultasIdIndexRoute = VetTeleconsultasIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VetTeleconsultasIdRoute,
} as any)
const VetTeleconsultasIdFinalizarRoute =
  VetTeleconsultasIdFinalizarRouteImport.update({
    id: '/finalizar',
    path: '/finalizar',
    getParentRoute: () => VetTeleconsultasIdRoute,
  } as any)
const VetTeleconsultasIdLiveRoute = VetTeleconsultasIdLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => VetTeleconsultasIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tutor': typeof TutorRouteWithChildren
  '/vet': typeof VetRouteWithChildren
  '/tutor/lembretes': typeof TutorLembretesRoute
  '/tutor/perfil': typeof TutorPerfilRoute
  '/tutor/teleconsultas': typeof TutorTeleconsultasRouteWithChildren
  '/vet/perfil': typeof VetPerfilRoute
  '/vet/pets': typeof VetPetsRouteWithChildren
  '/vet/teleconsultas': typeof VetTeleconsultasRouteWithChildren
  '/vet/tutores': typeof VetTutoresRouteWithChildren
  '/tutor/': typeof TutorIndexRoute
  '/vet/': typeof VetIndexRoute
  '/tutor/pets/$petId': typeof TutorPetsPetIdRoute
  '/tutor/teleconsultas/$id': typeof TutorTeleconsultasIdRouteWithChildren
  '/vet/pets/$petId': typeof VetPetsPetIdRoute
  '/vet/teleconsultas/$id': typeof VetTeleconsultasIdRouteWithChildren
  '/vet/tutores/$tutorId': typeof VetTutoresTutorIdRoute
  '/tutor/teleconsultas/': typeof TutorTeleconsultasIndexRoute
  '/vet/pets/': typeof VetPetsIndexRoute
  '/vet/teleconsultas/': typeof VetTeleconsultasIndexRoute
  '/vet/tutores/': typeof VetTutoresIndexRoute
  '/tutor/teleconsultas/$id/live': typeof TutorTeleconsultasIdLiveRoute
  '/vet/teleconsultas/$id/finalizar': typeof VetTeleconsultasIdFinalizarRoute
  '/vet/teleconsultas/$id/live': typeof VetTeleconsultasIdLiveRoute
  '/tutor/teleconsultas/$id/': typeof TutorTeleconsultasIdIndexRoute
  '/vet/teleconsultas/$id/': typeof VetTeleconsultasIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tutor/lembretes': typeof TutorLembretesRoute
  '/tutor/perfil': typeof TutorPerfilRoute
  '/vet/perfil': typeof VetPerfilRoute
  '/tutor': typeof TutorIndexRoute
  '/vet': typeof VetIndexRoute
  '/tutor/pets/$petId': typeof TutorPetsPetIdRoute
  '/vet/pets/$petId': typeof VetPetsPetIdRoute
  '/vet/tutores/$tutorId': typeof VetTutoresTutorIdRoute
  '/tutor/teleconsultas': typeof TutorTeleconsultasIndexRoute
  '/vet/pets': typeof VetPetsIndexRoute
  '/vet/teleconsultas': typeof VetTeleconsultasIndexRoute
  '/vet/tutores': typeof VetTutoresIndexRoute
  '/tutor/teleconsultas/$id/live': typeof TutorTeleconsultasIdLiveRoute
  '/vet/teleconsultas/$id/finalizar': typeof VetTeleconsultasIdFinalizarRoute
  '/vet/teleconsultas/$id/live': typeof VetTeleconsultasIdLiveRoute
  '/tutor/teleconsultas/$id': typeof TutorTeleconsultasIdIndexRoute
  '/vet/teleconsultas/$id': typeof VetTeleconsultasIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tutor': typeof TutorRouteWithChildren
  '/vet': typeof VetRouteWithChildren
  '/tutor/lembretes': typeof TutorLembretesRoute
  '/tutor/perfil': typeof TutorPerfilRoute
  '/tutor/teleconsultas': typeof TutorTeleconsultasRouteWithChildren
  '/vet/perfil': typeof VetPerfilRoute
  '/vet/pets': typeof VetPetsRouteWithChildren
  '/vet/teleconsultas': typeof VetTeleconsultasRouteWithChildren
  '/vet/tutores': typeof VetTutoresRouteWithChildren
  '/tutor/': typeof TutorIndexRoute
  '/vet/': typeof VetIndexRoute
  '/tutor/pets/$petId': typeof TutorPetsPetIdRoute
  '/tutor/teleconsultas/$id': typeof TutorTeleconsultasIdRouteWithChildren
  '/vet/pets/$petId': typeof VetPetsPetIdRoute
  '/vet/teleconsultas/$id': typeof VetTeleconsultasIdRouteWithChildren
  '/vet/tutores/$tutorId': typeof VetTutoresTutorIdRoute
  '/tutor/teleconsultas/': typeof TutorTeleconsultasIndexRoute
  '/vet/pets/': typeof VetPetsIndexRoute
  '/vet/teleconsultas/': typeof VetTeleconsultasIndexRoute
  '/vet/tutores/': typeof VetTutoresIndexRoute
  '/tutor/teleconsultas/$id/live': typeof TutorTeleconsultasIdLiveRoute
  '/vet/teleconsultas/$id/finalizar': typeof VetTeleconsultasIdFinalizarRoute
  '/vet/teleconsultas/$id/live': typeof VetTeleconsultasIdLiveRoute
  '/tutor/teleconsultas/$id/': typeof TutorTeleconsultasIdIndexRoute
  '/vet/teleconsultas/$id/': typeof VetTeleconsultasIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/tutor'
    | '/vet'
    | '/tutor/lembretes'
    | '/tutor/perfil'
    | '/tutor/teleconsultas'
    | '/vet/perfil'
    | '/vet/pets'
    | '/vet/teleconsultas'
    | '/vet/tutores'
    | '/tutor/'
    | '/vet/'
    | '/tutor/pets/$petId'
    | '/tutor/teleconsultas/$id'
    | '/vet/pets/$petId'
    | '/vet/teleconsultas/$id'
    | '/vet/tutores/$tutorId'
    | '/tutor/teleconsultas/'
    | '/vet/pets/'
    | '/vet/teleconsultas/'
    | '/vet/tutores/'
    | '/tutor/teleconsultas/$id/live'
    | '/vet/teleconsultas/$id/finalizar'
    | '/vet/teleconsultas/$id/live'
    | '/tutor/teleconsultas/$id/'
    | '/vet/teleconsultas/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/tutor/lembretes'
    | '/tutor/perfil'
    | '/vet/perfil'
    | '/tutor'
    | '/vet'
    | '/tutor/pets/$petId'
    | '/vet/pets/$petId'
    | '/vet/tutores/$tutorId'
    | '/tutor/teleconsultas'
    | '/vet/pets'
    | '/vet/teleconsultas'
    | '/vet/tutores'
    | '/tutor/teleconsultas/$id/live'
    | '/vet/teleconsultas/$id/finalizar'
    | '/vet/teleconsultas/$id/live'
    | '/tutor/teleconsultas/$id'
    | '/vet/teleconsultas/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/tutor'
    | '/vet'
    | '/tutor/lembretes'
    | '/tutor/perfil'
    | '/tutor/teleconsultas'
    | '/vet/perfil'
    | '/vet/pets'
    | '/vet/teleconsultas'
    | '/vet/tutores'
    | '/tutor/'
    | '/vet/'
    | '/tutor/pets/$petId'
    | '/tutor/teleconsultas/$id'
    | '/vet/pets/$petId'
    | '/vet/teleconsultas/$id'
    | '/vet/tutores/$tutorId'
    | '/tutor/teleconsultas/'
    | '/vet/pets/'
    | '/vet/teleconsultas/'
    | '/vet/tutores/'
    | '/tutor/teleconsultas/$id/live'
    | '/vet/teleconsultas/$id/finalizar'
    | '/vet/teleconsultas/$id/live'
    | '/tutor/teleconsultas/$id/'
    | '/vet/teleconsultas/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TutorRoute: typeof TutorRouteWithChildren
  VetRoute: typeof VetRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet': {
      id: '/vet'
      path: '/vet'
      fullPath: '/vet'
      preLoaderRoute: typeof VetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/': {
      id: '/tutor/'
      path: '/'
      fullPath: '/tutor/'
      preLoaderRoute: typeof TutorIndexRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/lembretes': {
      id: '/tutor/lembretes'
      path: '/lembretes'
      fullPath: '/tutor/lembretes'
      preLoaderRoute: typeof TutorLembretesRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/perfil': {
      id: '/tutor/perfil'
      path: '/perfil'
      fullPath: '/tutor/perfil'
      preLoaderRoute: typeof TutorPerfilRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/teleconsultas': {
      id: '/tutor/teleconsultas'
      path: '/teleconsultas'
      fullPath: '/tutor/teleconsultas'
      preLoaderRoute: typeof TutorTeleconsultasRouteImport
      parentRoute: typeof TutorRoute
    }
    '/vet/': {
      id: '/vet/'
      path: '/'
      fullPath: '/vet/'
      preLoaderRoute: typeof VetIndexRouteImport
      parentRoute: typeof VetRoute
    }
    '/vet/perfil': {
      id: '/vet/perfil'
      path: '/perfil'
      fullPath: '/vet/perfil'
      preLoaderRoute: typeof VetPerfilRouteImport
      parentRoute: typeof VetRoute
    }
    '/vet/pets': {
      id: '/vet/pets'
      path: '/pets'
      fullPath: '/vet/pets'
      preLoaderRoute: typeof VetPetsRouteImport
      parentRoute: typeof VetRoute
    }
    '/vet/teleconsultas': {
      id: '/vet/teleconsultas'
      path: '/teleconsultas'
      fullPath: '/vet/teleconsultas'
      preLoaderRoute: typeof VetTeleconsultasRouteImport
      parentRoute: typeof VetRoute
    }
    '/vet/tutores': {
      id: '/vet/tutores'
      path: '/tutores'
      fullPath: '/vet/tutores'
      preLoaderRoute: typeof VetTutoresRouteImport
      parentRoute: typeof VetRoute
    }
    '/tutor/pets/$petId': {
      id: '/tutor/pets/$petId'
      path: '/pets/$petId'
      fullPath: '/tutor/pets/$petId'
      preLoaderRoute: typeof TutorPetsPetIdRouteImport
      parentRoute: typeof TutorRoute
    }
    '/tutor/teleconsultas/': {
      id: '/tutor/teleconsultas/'
      path: '/'
      fullPath: '/tutor/teleconsultas/'
      preLoaderRoute: typeof TutorTeleconsultasIndexRouteImport
      parentRoute: typeof TutorTeleconsultasRoute
    }
    '/tutor/teleconsultas/$id': {
      id: '/tutor/teleconsultas/$id'
      path: '/$id'
      fullPath: '/tutor/teleconsultas/$id'
      preLoaderRoute: typeof TutorTeleconsultasIdRouteImport
      parentRoute: typeof TutorTeleconsultasRoute
    }
    '/vet/pets/': {
      id: '/vet/pets/'
      path: '/'
      fullPath: '/vet/pets/'
      preLoaderRoute: typeof VetPetsIndexRouteImport
      parentRoute: typeof VetPetsRoute
    }
    '/vet/pets/$petId': {
      id: '/vet/pets/$petId'
      path: '/$petId'
      fullPath: '/vet/pets/$petId'
      preLoaderRoute: typeof VetPetsPetIdRouteImport
      parentRoute: typeof VetPetsRoute
    }
    '/vet/teleconsultas/': {
      id: '/vet/teleconsultas/'
      path: '/'
      fullPath: '/vet/teleconsultas/'
      preLoaderRoute: typeof VetTeleconsultasIndexRouteImport
      parentRoute: typeof VetTeleconsultasRoute
    }
    '/vet/teleconsultas/$id': {
      id: '/vet/teleconsultas/$id'
      path: '/$id'
      fullPath: '/vet/teleconsultas/$id'
      preLoaderRoute: typeof VetTeleconsultasIdRouteImport
      parentRoute: typeof VetTeleconsultasRoute
    }
    '/vet/tutores/': {
      id: '/vet/tutores/'
      path: '/'
      fullPath: '/vet/tutores/'
      preLoaderRoute: typeof VetTutoresIndexRouteImport
      parentRoute: typeof VetTutoresRoute
    }
    '/vet/tutores/$tutorId': {
      id: '/vet/tutores/$tutorId'
      path: '/$tutorId'
      fullPath: '/vet/tutores/$tutorId'
      preLoaderRoute: typeof VetTutoresTutorIdRouteImport
      parentRoute: typeof VetTutoresRoute
    }
    '/tutor/teleconsultas/$id/': {
      id: '/tutor/teleconsultas/$id/'
      path: '/'
      fullPath: '/tutor/teleconsultas/$id/'
      preLoaderRoute: typeof TutorTeleconsultasIdIndexRouteImport
      parentRoute: typeof TutorTeleconsultasIdRoute
    }
    '/tutor/teleconsultas/$id/live': {
      id: '/tutor/teleconsultas/$id/live'
      path: '/live'
      fullPath: '/tutor/teleconsultas/$id/live'
      preLoaderRoute: typeof TutorTeleconsultasIdLiveRouteImport
      parentRoute: typeof TutorTeleconsultasIdRoute
    }
    '/vet/teleconsultas/$id/': {
      id: '/vet/teleconsultas/$id/'
      path: '/'
      fullPath: '/vet/teleconsultas/$id/'
      preLoaderRoute: typeof VetTeleconsultasIdIndexRouteImport
      parentRoute: typeof VetTeleconsultasIdRoute
    }
    '/vet/teleconsultas/$id/finalizar': {
      id: '/vet/teleconsultas/$id/finalizar'
      path: '/finalizar'
      fullPath: '/vet/teleconsultas/$id/finalizar'
      preLoaderRoute: typeof VetTeleconsultasIdFinalizarRouteImport
      parentRoute: typeof VetTeleconsultasIdRoute
    }
    '/vet/teleconsultas/$id/live': {
      id: '/vet/teleconsultas/$id/live'
      path: '/live'
      fullPath: '/vet/teleconsultas/$id/live'
      preLoaderRoute: typeof VetTeleconsultasIdLiveRouteImport
      parentRoute: typeof VetTeleconsultasIdRoute
    }
  }
}

interface TutorTeleconsultasIdRouteChildren {
  TutorTeleconsultasIdLiveRoute: typeof TutorTeleconsultasIdLiveRoute
  TutorTeleconsultasIdIndexRoute: typeof TutorTeleconsultasIdIndexRoute
}

const TutorTeleconsultasIdRouteChildren: TutorTeleconsultasIdRouteChildren = {
  TutorTeleconsultasIdLiveRoute: TutorTeleconsultasIdLiveRoute,
  TutorTeleconsultasIdIndexRoute: TutorTeleconsultasIdIndexRoute,
}

const TutorTeleconsultasIdRouteWithChildren =
  TutorTeleconsultasIdRoute._addFileChildren(TutorTeleconsultasIdRouteChildren)

interface TutorTeleconsultasRouteChildren {
  TutorTeleconsultasIdRoute: typeof TutorTeleconsultasIdRouteWithChildren
  TutorTeleconsultasIndexRoute: typeof TutorTeleconsultasIndexRoute
}

const TutorTeleconsultasRouteChildren: TutorTeleconsultasRouteChildren = {
  TutorTeleconsultasIdRoute: TutorTeleconsultasIdRouteWithChildren,
  TutorTeleconsultasIndexRoute: TutorTeleconsultasIndexRoute,
}

const TutorTeleconsultasRouteWithChildren =
  TutorTeleconsultasRoute._addFileChildren(TutorTeleconsultasRouteChildren)

interface TutorRouteChildren {
  TutorLembretesRoute: typeof TutorLembretesRoute
  TutorPerfilRoute: typeof TutorPerfilRoute
  TutorTeleconsultasRoute: typeof TutorTeleconsultasRouteWithChildren
  TutorIndexRoute: typeof TutorIndexRoute
  TutorPetsPetIdRoute: typeof TutorPetsPetIdRoute
}

const TutorRouteChildren: TutorRouteChildren = {
  TutorLembretesRoute: TutorLembretesRoute,
  TutorPerfilRoute: TutorPerfilRoute,
  TutorTeleconsultasRoute: TutorTeleconsultasRouteWithChildren,
  TutorIndexRoute: TutorIndexRoute,
  TutorPetsPetIdRoute: TutorPetsPetIdRoute,
}

const TutorRouteWithChildren = TutorRoute._addFileChildren(TutorRouteChildren)

interface VetPetsRouteChildren {
  VetPetsPetIdRoute: typeof VetPetsPetIdRoute
  VetPetsIndexRoute: typeof VetPetsIndexRoute
}

const VetPetsRouteChildren: VetPetsRouteChildren = {
  VetPetsPetIdRoute: VetPetsPetIdRoute,
  VetPetsIndexRoute: VetPetsIndexRoute,
}

const VetPetsRouteWithChildren =
  VetPetsRoute._addFileChildren(VetPetsRouteChildren)

interface VetTeleconsultasIdRouteChildren {
  VetTeleconsultasIdFinalizarRoute: typeof VetTeleconsultasIdFinalizarRoute
  VetTeleconsultasIdLiveRoute: typeof VetTeleconsultasIdLiveRoute
  VetTeleconsultasIdIndexRoute: typeof VetTeleconsultasIdIndexRoute
}

const VetTeleconsultasIdRouteChildren: VetTeleconsultasIdRouteChildren = {
  VetTeleconsultasIdFinalizarRoute: VetTeleconsultasIdFinalizarRoute,
  VetTeleconsultasIdLiveRoute: VetTeleconsultasIdLiveRoute,
  VetTeleconsultasIdIndexRoute: VetTeleconsultasIdIndexRoute,
}

const VetTeleconsultasIdRouteWithChildren =
  VetTeleconsultasIdRoute._addFileChildren(VetTeleconsultasIdRouteChildren)

interface VetTeleconsultasRouteChildren {
  VetTeleconsultasIdRoute: typeof VetTeleconsultasIdRouteWithChildren
  VetTeleconsultasIndexRoute: typeof VetTeleconsultasIndexRoute
}

const VetTeleconsultasRouteChildren: VetTeleconsultasRouteChildren = {
  VetTeleconsultasIdRoute: VetTeleconsultasIdRouteWithChildren,
  VetTeleconsultasIndexRoute: VetTeleconsultasIndexRoute,
}

const VetTeleconsultasRouteWithChildren =
  VetTeleconsultasRoute._addFileChildren(VetTeleconsultasRouteChildren)

interface VetTutoresRouteChildren {
  VetTutoresTutorIdRoute: typeof VetTutoresTutorIdRoute
  VetTutoresIndexRoute: typeof VetTutoresIndexRoute
}

const VetTutoresRouteChildren: VetTutoresRouteChildren = {
  VetTutoresTutorIdRoute: VetTutoresTutorIdRoute,
  VetTutoresIndexRoute: VetTutoresIndexRoute,
}

const VetTutoresRouteWithChildren = VetTutoresRoute._addFileChildren(
  VetTutoresRouteChildren,
)

interface VetRouteChildren {
  VetPerfilRoute: typeof VetPerfilRoute
  VetPetsRoute: typeof VetPetsRouteWithChildren
  VetTeleconsultasRoute: typeof VetTeleconsultasRouteWithChildren
  VetTutoresRoute: typeof VetTutoresRouteWithChildren
  VetIndexRoute: typeof VetIndexRoute
}

const VetRouteChildren: VetRouteChildren = {
  VetPerfilRoute: VetPerfilRoute,
  VetPetsRoute: VetPetsRouteWithChildren,
  VetTeleconsultasRoute: VetTeleconsultasRouteWithChildren,
  VetTutoresRoute: VetTutoresRouteWithChildren,
  VetIndexRoute: VetIndexRoute,
}

const VetRouteWithChildren = VetRoute._addFileChildren(VetRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TutorRoute: TutorRouteWithChildren,
  VetRoute: VetRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
